[workspace]
resolver = "3"
members = [
    "nih",
    "demo",
    "examples/grass",
    "examples/normal_mapping",
    "examples/particles",
    "examples/skybox",
    "examples/texture_filtering",
]

[profile.release]
debug = "full"